name: Build/Release
on: [push]

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Install Node.js
        uses: actions/setup-node@v4 # Actualizado a v4
        with:
          node-version: 20 # Usamos una versión de Node estable y moderna

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # ¡LA SOLUCIÓN AQUÍ! Actualizado a v4
        with:
          name: FactuApp-${{ matrix.os }}
          path: out/make/