name: Build/Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    # ESTO ARREGLA EL ERROR DE PERMISOS
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Actualizado a la versión más moderna

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run make

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.dmg
            out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}